[default]
DEBUG = false
TITLE = "Top 10 songs - from Genius API"
SECRET_KEY = "Pl3453Ch4ng3"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "confitec_teste.ext.restapi:init_app",
]

[development]
EXTENSIONS = [
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
